#!/usr/bin/env bash
# ----------------------------------------------------------------------
#  PayHSM — build + smoke-test script
#  Runs in WSL Ubuntu 24.04 against ~/payhsm/payhsm.
#  Generated by the PayHSM integration pass.
# ----------------------------------------------------------------------

set -euo pipefail

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[0;33m'; NC='\033[0m'
say() { printf "${GREEN}[payhsm]${NC} %s\n" "$*"; }
warn(){ printf "${YELLOW}[payhsm]${NC} %s\n" "$*"; }
die() { printf "${RED}[payhsm]${NC} %s\n" "$*"; exit 1; }

cd "$(dirname "$(readlink -f "$0")")"
REPO="$PWD"
say "Repo root: $REPO"

# ----------------------------------------------------------------------
# 1. Prerequisites
# ----------------------------------------------------------------------
need_pkg() { dpkg -s "$1" >/dev/null 2>&1 || MISSING+=("$1"); }
MISSING=()
need_pkg build-essential
need_pkg autoconf
need_pkg automake
need_pkg libtool
need_pkg pkg-config
need_pkg libssl-dev
need_pkg libsqlite3-dev
need_pkg opensc          # provides pkcs11-tool
if [ ${#MISSING[@]} -gt 0 ]; then
    warn "Missing packages: ${MISSING[*]}"
    warn "Install with:  sudo apt update && sudo apt install -y ${MISSING[*]}"
    die  "Aborting — install the missing packages then re-run this script."
fi

# ----------------------------------------------------------------------
# 2. Configure & build
# ----------------------------------------------------------------------
if [ ! -f configure ]; then
    say "Running autogen.sh"
    ./autogen.sh
fi
if [ ! -f Makefile ]; then
    say "Running configure"
    ./configure --with-crypto-backend=openssl \
                --with-objectstore-backend-db \
                --disable-non-paged-memory
fi
say "Building libsofthsm2.so (this can take a couple of minutes)"
make -j"$(nproc)"

LIB=src/lib/.libs/libsofthsm2.so
[ -f "$LIB" ] || die "Build did not produce $LIB"
say "Built $LIB ($(stat -c %s "$LIB") bytes)"

# ----------------------------------------------------------------------
# 3. PayHSM symbols sanity check
# ----------------------------------------------------------------------
say "Checking PayHSM exports …"
for sym in PayHSM_is_ready PayHSM_version PayHSM_PIN_translate \
           PayHSM_ARQC_verify PayHSM_MAC_calculate PayHSM_PIN_build \
           PayHSM_EMV_derive_sk_ac PayHSM_EMV_compute_arqc ; do
    nm -D --defined-only "$LIB" | grep -q " T $sym\$" \
        || die "Missing exported symbol: $sym"
done
say "All PayHSM_* symbols exported."

# ----------------------------------------------------------------------
# 4. PKCS#11 smoke test (uses a throw-away token dir under /tmp)
# ----------------------------------------------------------------------
TOKEN_DIR=$(mktemp -d -t payhsm-XXXXXX)
CONF=$TOKEN_DIR/softhsm2.conf
cat >"$CONF" <<EOF
directories.tokendir = $TOKEN_DIR
objectstore.backend = file
log.level = INFO
EOF
export SOFTHSM2_CONF=$CONF
say "Using throw-away token dir: $TOKEN_DIR"

# softhsm2-util might not be on the install-less build path, so call the
# in-tree binary
SOFTHSM2_UTIL=src/bin/util/softhsm2-util
[ -x "$SOFTHSM2_UTIL" ] || die "Build did not produce $SOFTHSM2_UTIL"

# softhsm2-util defaults to dlopen("/usr/local/lib/softhsm/libsofthsm2.so").
# We haven't `make install`ed, so we point it at the in-tree .so via --module.
"$SOFTHSM2_UTIL" --module "$LIB" --init-token --free \
                 --label payhsm --so-pin 1234 --pin 5678 \
    || die "softhsm2-util --init-token failed"

say "Token initialised. Running pkcs11-tool --test …"
pkcs11-tool --module "$LIB" --login --pin 5678 --test \
    || warn "pkcs11-tool --test returned non-zero (some optional mechs may not be supported — check output above)"

say "BUILD + PKCS#11 SMOKE TEST PASSED"
echo
echo "  libsofthsm2.so : $REPO/$LIB"
echo "  Throw-away cfg : $CONF (delete $TOKEN_DIR when you're done)"
echo
echo "Next: cd tools/payhsm_demo && ./run_demo.sh"
